# Generated by Django 4.2.10 on 2024-02-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
