# Generated by Django 4.2.10 on 2024-02-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_user_avatar_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=512)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.user')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.comment'),
        ),
    ]
